apiVersion: v1
kind: Namespace
metadata:
  name: gateway-dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-dns
  namespace: gateway-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-dns
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes", "grpcroutes", "gateways"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes", "grpcroutes"]
    verbs: ["update"]  # for finalizers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gateway-dns
subjects:
  - kind: ServiceAccount
    name: gateway-dns
    namespace: gateway-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gateway-dns
  name: gateway-dns
  namespace: gateway-dns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-dns
  template:
    metadata:
      labels:
        app: gateway-dns
    spec:
      serviceAccount: gateway-dns
      containers:
      - image: mmouru/gateway-dns:latest
        name: dns-store
        ports:
        - containerPort: 5353
          protocol: UDP
          name: dns-udp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway-dns
  name: gateway-dns
  namespace: gateway-dns
spec:
  type: LoadBalancer
  selector:
    app: gateway-dns
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: dns-udp

